---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingressgateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: egressgateway
#   namespace: istio-system
# spec:
#   selector:
#     istio: egressgateway
#   servers:
#     - port:
#         number: 80
#         name: http
#         protocol: HTTP
#       hosts:
#         - "*"
#     - port:
#         number: 443
#         name: tls
#         protocol: HTTPS
#       hosts:
#         - "*"
#       tls:
#         mode: PASSTHROUGH
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#   name: egressgateway
#   namespace: istio-system
# spec:
#   host: istio-egressgateway.istio-system.svc.cluster.local
