---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: k3s-default
image: docker.io/rancher/k3s:v1.27.4-k3s1
servers: 1
agents: 2
kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6550"
ports:
  - port: 9080:80
    nodeFilters:
      - loadbalancer
  - port: 9443:443
    nodeFilters:
      - loadbalancer
volumes:
  - volume: ${CURRENT_DIR}/manifests:/var/lib/rancher/k3s/server/manifests/extra
    nodeFilters:
      - server:*
options:
  k3d:
    wait: true
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
  runtime:
    ulimits:
      - name: nofile
        soft: 26677
        hard: 26677
