apiVersion: v1
kind: Namespace
metadata:
  name: security
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  version: 1.12.4
  chart: cert-manager
  targetNamespace: security
  valuesContent: |-
    installCRDs: true
