apiVersion: v1
kind: Namespace
metadata:
  name: tracing
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tempo
  namespace: kube-system
spec:
  repo: https://grafana.github.io/helm-charts
  version: 1.6.0
  chart: tempo
  targetNamespace: tracing
  valuesContent: |-
    tempoQuery:
      enabled: true
    tempo:
      receivers:
        zipkin:
      metricsGenerator:
        enabled: true
        remoteWriteUrl: http://prometheus-operator-prometheus.monitoring:9090/api/v1/write
